const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let deals=[],map,markers=[]; const now=()=>new Date();
function mins(t){let[a,b]=t.split(':').map(Number);return a*60+b} function active(d,dt=now()){let m=dt.getHours()*60+dt.getMinutes();return d.days.includes(dt.getDay())&&m>=mins(d.start)&&m<mins(d.end)}
function fmt(t){let[h,m]=t.split(':').map(Number),ap=h>=12?'PM':'AM';h=h%12||12;return `${h}${m?':'+String(m).padStart(2,'0'):''} ${ap}`}
function state(){let p=new URLSearchParams(location.search);return {when:p.get('when')||'today',q:p.get('q')||'',inc:p.get('inc')?.split(',').filter(Boolean)||[],tod:p.get('tod')?.split(',').filter(Boolean)||[],sort:p.get('sort')||'best'}}
function writeState(s){let p=new URLSearchParams();if(s.when!='today')p.set('when',s.when);if(s.q)p.set('q',s.q);if(s.inc.length)p.set('inc',s.inc.join(','));if(s.tod.length)p.set('tod',s.tod.join(','));if(s.sort!='best')p.set('sort',s.sort);history.replaceState(null,'',location.pathname+(p.toString()?'?'+p:''))}
function render(){let s=state(),dt=now(),day=dt.getDay(); $('#q').value=s.q; $('#sort').value=s.sort; $$('#whenChips button').forEach(b=>b.classList.toggle('active',b.dataset.when==s.when)); $$('.inc').forEach(x=>x.checked=s.inc.includes(x.value));$$('.tod').forEach(x=>x.checked=s.tod.includes(x.value)); let a=deals.filter(d=>{if(s.when==='now'&&!active(d,dt))return false;if(s.when==='today'&&!d.days.includes(day))return false;if(s.q&&!(`${d.venue} ${d.deal} ${d.area}`).toLowerCase().includes(s.q.toLowerCase()))return false;if(s.inc.length&&!s.inc.every(x=>d.includes.includes(x)))return false;let st=mins(d.start);if(s.tod.includes('aft')&&!(st>=12*60&&st<17*60))return false;if(s.tod.includes('eve')&&!(st>=17*60))return false;return true}); if(s.sort==='az')a.sort((x,y)=>x.venue.localeCompare(y.venue));else if(s.sort==='time')a.sort((x,y)=>mins(x.start)-mins(y.start));else a.sort((x,y)=>(active(y,dt)-active(x,dt))||(mins(x.start)-mins(y.start))); $('#list').innerHTML=a.length?a.map(d=>`<article class='card'><div class='top'><div><div class='venue'>${d.venue}</div><div class='area'>${d.area} · ${d.address}</div></div><span class='status ${active(d,dt)?'on':''}'>${active(d,dt)?'ON NOW':fmt(d.start)+'–'+fmt(d.end)}</span></div><div class='deal'>${d.deal}</div><div class='meta'>${dayText(d.days)} · ${fmt(d.start)}–${fmt(d.end)}</div><div class='tags'>${d.includes.map(x=>`<span class='tag'>${x}</span>`).join('')}</div><a class='source' target='_blank' rel='noopener' href='${d.source}'>Check source ↗</a></article>`).join(''):`<div class='empty'>No matching 93108 specials.</div>`; draw(a)}
function dayText(ds){if(ds.length===7)return'Daily';let n=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];return ds.map(x=>n[x]).join(', ')}
function draw(a){if(!map)return;markers.forEach(m=>m.remove());markers=a.map(d=>L.marker([d.lat,d.lng]).addTo(map).bindPopup(`<b>${d.venue}</b><br>${fmt(d.start)}–${fmt(d.end)}<br>${d.deal}`))}
fetch('deals.json').then(r=>r.json()).then(x=>{deals=x;map=L.map('map').setView([34.4214,-119.6445],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);render()});
$('#q').oninput=e=>{let s=state();s.q=e.target.value;writeState(s);render()};$('#whenChips').onclick=e=>{if(e.target.dataset.when){let s=state();s.when=e.target.dataset.when;writeState(s);render()}};$('#filtersBtn').onclick=()=>$('#filterPanel').classList.toggle('hidden');$$('.inc,.tod').forEach(x=>x.onchange=()=>{let s=state();s.inc=$$('.inc:checked').map(x=>x.value);s.tod=$$('.tod:checked').map(x=>x.value);writeState(s);render()});$('#sort').onchange=e=>{let s=state();s.sort=e.target.value;writeState(s);render()};$('#clear').onclick=()=>{history.replaceState(null,'',location.pathname);render()};$('#mapToggle').onclick=()=>{document.body.classList.toggle('mapmode');setTimeout(()=>map&&map.invalidateSize(),100)};
